"""Added approval status to placement drive

Revision ID: 23b7c2c361a5
Revises: b6ac4725cc92
Create Date: 2026-07-24 23:49:49.791622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b7c2c361a5'
down_revision = 'b6ac4725cc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
