"""Add interview fields to application

Revision ID: bc9ca18473bf
Revises: 23b7c2c361a5
Create Date: 2026-07-31 15:44:51.639295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9ca18473bf'
down_revision = '23b7c2c361a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('interview_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('interview_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('interview_location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('interview_location')
        batch_op.drop_column('interview_mode')
        batch_op.drop_column('interview_time')
        batch_op.drop_column('interview_date')

    # ### end Alembic commands ###
